set = set()

n = int(input("Enter Number  : "))
set.add(n)
n = int(input("Enter Number 2 : "))
set.add(n)
n = int(input("Enter Number 3 : "))
set.add(n)
n = int(input("Enter Number 4 : "))
set.add(n)
n = int(input("Enter Number 5 : "))
set.add(n)
n = int(input("Enter Number 6 : "))
set.add(n)
n = int(input("Enter Number 7 : "))
set.add(n)
n = int(input("Enter Number 8 : "))
set.add(n)

print(f"Unique Number set are : {set}")
